<a href="https://colab.research.google.com/github/eunseojeon/AI_Coding_for_Autonomous_Driving_Class/blob/main/0703_%EB%AF%B8%EC%85%98_NumPy_%EC%BD%94%EB%93%9C_%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1단계: NumPy 기초 - 자율주행 센서 데이터 처리
# 코랩에서 바로 실행 가능!

import numpy as np
print("🚗 자율주행 NumPy 기초 학습 시작!")
print("📦 NumPy 버전:", np.__version__)
print()


🚗 자율주행 NumPy 기초 학습 시작!
📦 NumPy 버전: 2.0.2



In [ ]:
# ===== 1. NumPy 배열 기초 =====
print("=== 1. NumPy 배열 기초 ===")

# 1-1. 리스트를 NumPy 배열로 변환
print("📊 1-1. 센서 거리 데이터")
sensor_distances = [8.5, 12.3, 15.7, 2.1, 9.8]  # 파이썬 리스트
print("원본 리스트:", sensor_distances)
print("리스트 타입:", type(sensor_distances))

# NumPy 배열로 변환
np_distances = np.array(sensor_distances)
print("NumPy 배열:", np_distances)
print("NumPy 타입:", type(np_distances))
print("배열 모양:", np_distances.shape)
print("배열 크기:", np_distances.size)
print()

# 1-2. 직접 배열 생성
print("📊 1-2. 다양한 배열 생성 방법")
zeros_array = np.zeros(5)  # 0으로 채운 배열
ones_array = np.ones(4)    # 1로 채운 배열
range_array = np.arange(0, 10, 2)  # 0부터 10까지 2씩 증가
linspace_array = np.linspace(0, 100, 5)  # 0부터 100까지 5개 구간

print("0으로 채운 배열:", zeros_array)
print("1로 채운 배열:", ones_array)
print("범위 배열 (0~10, 2씩):", range_array)
print("구간 배열 (0~100, 5개):", linspace_array)
print()



=== 1. NumPy 배열 기초 ===
📊 1-1. 센서 거리 데이터
원본 리스트: [8.5, 12.3, 15.7, 2.1, 9.8]
리스트 타입: <class 'list'>
NumPy 배열: [ 8.5 12.3 15.7  2.1  9.8]
NumPy 타입: <class 'numpy.ndarray'>
배열 모양: (5,)
배열 크기: 5

📊 1-2. 다양한 배열 생성 방법
0으로 채운 배열: [0. 0. 0. 0. 0.]
1로 채운 배열: [1. 1. 1. 1.]
범위 배열 (0~10, 2씩): [0 2 4 6 8]
구간 배열 (0~100, 5개): [  0.  25.  50.  75. 100.]



In [ ]:
# ===== 2. 배열 연산 =====
print("=== 2. 배열 연산 ===")

# 2-1. 기본 산술 연산
print("📊 2-1. 센서 데이터 계산")
distances = np.array([8.5, 12.3, 15.7, 2.1, 9.8])
print("원본 거리:", distances)

# 모든 값에 동일한 연산 적용, (브로드캐스팅)
distances_in_cm = distances * 100  # 미터를 센티미터로
distances_plus_offset = distances + 1.5  # 모든 값에 1.5 더하기

print("센티미터 변환:", distances_in_cm)
print("오프셋 적용:", distances_plus_offset)
print()

# 2-2. 배열 간 연산
print("📊 2-2. 두 센서 데이터 비교")
front_sensors = np.array([8.5, 12.3, 15.7])
rear_sensors = np.array([6.2, 9.1, 13.4])

print("전방 센서:", front_sensors)
print("후방 센서:", rear_sensors)
print("센서 차이:", front_sensors - rear_sensors)
print("평균 거리:", (front_sensors + rear_sensors) / 2)
print()


=== 2. 배열 연산 ===
📊 2-1. 센서 데이터 계산
원본 거리: [ 8.5 12.3 15.7  2.1  9.8]
센티미터 변환: [ 850. 1230. 1570.  210.  980.]
오프셋 적용: [10.  13.8 17.2  3.6 11.3]

📊 2-2. 두 센서 데이터 비교
전방 센서: [ 8.5 12.3 15.7]
후방 센서: [ 6.2  9.1 13.4]
센서 차이: [2.3 3.2 2.3]
평균 거리: [ 7.35 10.7  14.55]



In [ ]:
# ===== 3. 배열 통계 함수 =====
print("=== 3. 배열 통계 함수 ===")

print("📊 3-1. 센서 데이터 통계")
all_distances = np.array([8.5, 12.3, 15.7, 2.1, 9.8, 6.2, 11.4, 3.9])
print("전체 센서 데이터:", all_distances)

print("최대값:", np.max(all_distances))
print("최소값:", np.min(all_distances))
print("평균값:", np.mean(all_distances))
print("중간값:", np.median(all_distances))
print("표준편차:", np.std(all_distances))
print("합계:", np.sum(all_distances))
print()

# 3-2. 인덱스 찾기
print("📊 3-2. 특정 값의 위치 찾기")
max_index = np.argmax(all_distances)  # 최대값의 인덱스
min_index = np.argmin(all_distances)  # 최소값의 인덱스

print(f"가장 먼 거리: {all_distances[max_index]}m (인덱스: {max_index})")
print(f"가장 가까운 거리: {all_distances[min_index]}m (인덱스: {min_index})")
print()

=== 3. 배열 통계 함수 ===
📊 3-1. 센서 데이터 통계
전체 센서 데이터: [ 8.5 12.3 15.7  2.1  9.8  6.2 11.4  3.9]
최대값: 15.7
최소값: 2.1
평균값: 8.7375
중간값: 9.15
표준편차: 4.232888346035128
합계: 69.9

📊 3-2. 특정 값의 위치 찾기
가장 먼 거리: 15.7m (인덱스: 2)
가장 가까운 거리: 2.1m (인덱스: 3)



In [ ]:
# ===== 4. 조건부 필터링 =====
print("=== 4. 조건부 필터링 ===")

# 4-1. 조건으로 데이터 선택
print("📊 4-1. 위험 거리 감지 (5m 이하)")
dangerous_mask = all_distances <= 5.0  # 조건 마스크 생성
print("조건 마스크:", dangerous_mask)

dangerous_distances = all_distances[dangerous_mask]  # 조건에 맞는 값들
safe_distances = all_distances[all_distances > 5.0]  # 한 줄로 표현

print("위험 거리:", dangerous_distances)
print("안전 거리:", safe_distances)
print("위험 센서 개수:", len(dangerous_distances))
print("안전 센서 개수:", len(safe_distances))
print()

# 4-2. 복합 조건
print("📊 4-2. 복합 조건 (5m 이하 OR 15m 이상)")
extreme_distances = all_distances[(all_distances <= 5.0) | (all_distances >= 15.0)]
print("극한 거리 (너무 가깝거나 너무 먼):", extreme_distances)

normal_distances = all_distances[(all_distances > 5.0) & (all_distances < 15.0)]
print("정상 범위 거리:", normal_distances)
print()

=== 4. 조건부 필터링 ===
📊 4-1. 위험 거리 감지 (5m 이하)
조건 마스크: [False False False  True False False False  True]
위험 거리: [2.1 3.9]
안전 거리: [ 8.5 12.3 15.7  9.8  6.2 11.4]
위험 센서 개수: 2
안전 센서 개수: 6

📊 4-2. 복합 조건 (5m 이하 OR 15m 이상)
극한 거리 (너무 가깝거나 너무 먼): [15.7  2.1  3.9]
정상 범위 거리: [ 8.5 12.3  9.8  6.2 11.4]



In [ ]:
# ===== 5.센서 배열 생성 =====
print("=== 5.센서 배열 생성 ===")

# 5-1. 2D 센서 배열 생성
print("📊 5-1. 다방향 센서 매트릭스")
# 4x4 센서 그리드 (전방, 우측, 후방, 좌측)
sensor_matrix = np.array([
    [8.5, 12.3, 15.7, 11.2],  # 전방 4개 센서
    [9.1, 6.8, 13.4, 7.5],    # 우측 4개 센서
    [10.2, 8.9, 14.1, 9.7],   # 후방 4개 센서
    [7.3, 11.6, 12.8, 6.4]    # 좌측 4개 센서
])

print("센서 매트릭스:")
print(sensor_matrix)
print("매트릭스 모양:", sensor_matrix.shape)  # (행, 열)
print("총 센서 개수:", sensor_matrix.size)
print()

# 5-2. 행/열별 연산
print("📊 5-2. 방향별 센서 분석")
print("전방 센서 (첫 번째 행):", sensor_matrix[0])
print("전방 센서 평균:", np.mean(sensor_matrix[0]))

print("모든 방향 평균:")
direction_names = ['전방', '우측', '후방', '좌측']
for i, direction in enumerate(direction_names):
    avg_distance = np.mean(sensor_matrix[i])
    print(f"  {direction}: {avg_distance:.2f}m")
print()

# 5-3. 전체 매트릭스 연산
print("📊 5-3. 전체 센서 통계")
print("전체 평균:", np.mean(sensor_matrix))
print("전체 최대:", np.max(sensor_matrix))
print("전체 최소:", np.min(sensor_matrix))

# 각 열 (센서 위치)별 평균
column_averages = np.mean(sensor_matrix, axis=0)  # axis=0: 행 방향으로 평균
print("센서 위치별 평균:", column_averages)

# 각 행 (방향)별 평균
row_averages = np.mean(sensor_matrix, axis=1)  # axis=1: 열 방향으로 평균
print("방향별 평균:", row_averages)
print()

=== 5.센서 배열 생성 ===
📊 5-1. 다방향 센서 매트릭스
센서 매트릭스:
[[ 8.5 12.3 15.7 11.2]
 [ 9.1  6.8 13.4  7.5]
 [10.2  8.9 14.1  9.7]
 [ 7.3 11.6 12.8  6.4]]
매트릭스 모양: (4, 4)
총 센서 개수: 16

📊 5-2. 방향별 센서 분석
전방 센서 (첫 번째 행): [ 8.5 12.3 15.7 11.2]
전방 센서 평균: 11.925
모든 방향 평균:
  전방: 11.93m
  우측: 9.20m
  후방: 10.73m
  좌측: 9.53m

📊 5-3. 전체 센서 통계
전체 평균: 10.34375
전체 최대: 15.7
전체 최소: 6.4
센서 위치별 평균: [ 8.775  9.9   14.     8.7  ]
방향별 평균: [11.925  9.2   10.725  9.525]



In [ ]:
# ===== 6. GPS 좌표 처리 =====
print("=== 6. GPS 좌표 처리 ===")

# 6-1. 위치 벡터
print("📊 6-1. 현재 위치와 목적지")
current_pos = np.array([127.123, 37.456])  # [경도, 위도]
destination = np.array([127.145, 37.478])

print("현재 위치:", current_pos)
print("목적지:", destination)
# 이동 벡터 계산
movement_vector = destination - current_pos
print("이동 벡터:", movement_vector)
print("경도 이동:", movement_vector[0])
print("위도 이동:", movement_vector[1])
print()

# 6-2. 거리 계산
print("📊 6-2. 직선 거리 계산")
# 유클리드 거리 공식: sqrt((x2-x1)^2 + (y2-y1)^2)
distance = np.sqrt(np.sum(movement_vector**2))
print("직선 거리:", distance)

# 맨하탄 거리 (격자 도로에서 실제 이동 거리)
manhattan_distance = np.sum(np.abs(movement_vector))
print("맨하탄 거리:", manhattan_distance)
print()


=== 6. GPS 좌표 처리 ===
📊 6-1. 현재 위치와 목적지
현재 위치: [127.123  37.456]
목적지: [127.145  37.478]
이동 벡터: [0.022 0.022]
경도 이동: 0.02199999999999136
위도 이동: 0.021999999999998465

📊 6-2. 직선 거리 계산
직선 거리: 0.031112698372200896
맨하탄 거리: 0.043999999999989825



In [ ]:
# ===== 7. 경로 생성 =====
print("=== 7. 경로 생성 ===")

# 7-1. 직선 경로 포인트 생성
print("📊 7-1. 자동 경로 생성")
num_waypoints = 8
route_x = np.linspace(current_pos[0], destination[0], num_waypoints)
route_y = np.linspace(current_pos[1], destination[1], num_waypoints)

print("경로 X 좌표:", route_x)
print("경로 Y 좌표:", route_y)
# 좌표를 하나의 2D 배열로 결합
route_points = np.column_stack((route_x, route_y))
print("경로 포인트 매트릭스:")
print(route_points)
print("경로 모양:", route_points.shape)
print()
# 7-2. 각 구간별 거리 계산
print("📊 7-2. 구간별 이동 거리")
# 연속된 포인트 간 거리 계산
segment_distances = []
for i in range(len(route_points) - 1):
    point1 = route_points[i]
    point2 = route_points[i + 1]
    segment_dist = np.sqrt(np.sum((point2 - point1)**2))
    segment_distances.append(segment_dist)
    print(f"구간 {i+1}: {segment_dist:.6f}")

total_route_distance = np.sum(segment_distances)
print(f"총 경로 거리: {total_route_distance:.6f}")
print()

=== 7. 경로 생성 ===
📊 7-1. 자동 경로 생성
경로 X 좌표: [127.123      127.12614286 127.12928571 127.13242857 127.13557143
 127.13871429 127.14185714 127.145     ]
경로 Y 좌표: [37.456      37.45914286 37.46228571 37.46542857 37.46857143 37.47171429
 37.47485714 37.478     ]
경로 포인트 매트릭스:
[[127.123       37.456     ]
 [127.12614286  37.45914286]
 [127.12928571  37.46228571]
 [127.13242857  37.46542857]
 [127.13557143  37.46857143]
 [127.13871429  37.47171429]
 [127.14185714  37.47485714]
 [127.145       37.478     ]]
경로 모양: (8, 2)

📊 7-2. 구간별 이동 거리
구간 1: 0.004445
구간 2: 0.004445
구간 3: 0.004445
구간 4: 0.004445
구간 5: 0.004445
구간 6: 0.004445
구간 7: 0.004445
총 경로 거리: 0.031113



In [ ]:
# ===== 8. 실전 응용 - 장애물 회피 =====
print("=== 8. 실전 응용 - 장애물 회피 ===")

# 8-1. 장애물 위치
print("📊 8-1. 장애물 감지 및 분석")
obstacles = np.array([
    [127.130, 37.460],  # 장애물 1
    [127.135, 37.465],  # 장애물 2
    [127.140, 37.470]   # 장애물 3
])

print("감지된 장애물 위치:")
print(obstacles)
# 현재 위치에서 각 장애물까지의 거리
obstacle_distances = []
for i, obstacle in enumerate(obstacles):
    dist = np.sqrt(np.sum((obstacle - current_pos)**2))
    obstacle_distances.append(dist)
    print(f"장애물 {i+1}까지 거리: {dist:.6f}")

# 가장 가까운 장애물 찾기
closest_obstacle_index = np.argmin(obstacle_distances)
closest_distance = obstacle_distances[closest_obstacle_index]
print(f"가장 가까운 장애물: {closest_obstacle_index+1}번 (거리: {closest_distance:.6f})")
print()
# 8-2. 안전 반경 체크
print("📊 8-2. 안전 반경 체크")
safety_radius = 0.005  # 대략 500m 정도
dangerous_obstacles = []

for i, dist in enumerate(obstacle_distances):
    if dist <= safety_radius:
        dangerous_obstacles.append(i+1)
        print(f"⚠️ 장애물 {i+1}: 위험 구역 (거리: {dist:.6f})")
    else:
        print(f"✅ 장애물 {i+1}: 안전 (거리: {dist:.6f})")

if dangerous_obstacles:
    print(f"총 {len(dangerous_obstacles)}개 장애물이 위험 구역에 있습니다!")
else:
    print("모든 장애물이 안전 거리에 있습니다.")
print()

print("🎓 NumPy 기초 학습 완료!")
print("📚 학습한 내용:")
print("   ✅ 배열 생성 및 기본 연산")
print("   ✅ 통계 함수 (평균, 최대, 최소 등)")
print("   ✅ 조건부 필터링 (위험 감지)")
print("   ✅ 2D 배열 (센서 매트릭스)")
print("   ✅ GPS 좌표 처리")
print("   ✅ 경로 생성 및 거리 계산")
print("   ✅ 장애물 감지 및 안전 반경 체크")
print("\n🚗 다음은 Pandas로 주행 데이터를 분석해보겠습니다!")
print("="*60)

=== 8. 실전 응용 - 장애물 회피 ===
📊 8-1. 장애물 감지 및 분석
감지된 장애물 위치:
[[127.13   37.46 ]
 [127.135  37.465]
 [127.14   37.47 ]]
장애물 1까지 거리: 0.008062
장애물 2까지 거리: 0.015000
장애물 3까지 거리: 0.022023
가장 가까운 장애물: 1번 (거리: 0.008062)

📊 8-2. 안전 반경 체크
✅ 장애물 1: 안전 (거리: 0.008062)
✅ 장애물 2: 안전 (거리: 0.015000)
✅ 장애물 3: 안전 (거리: 0.022023)
모든 장애물이 안전 거리에 있습니다.

🎓 NumPy 기초 학습 완료!
📚 학습한 내용:
   ✅ 배열 생성 및 기본 연산
   ✅ 통계 함수 (평균, 최대, 최소 등)
   ✅ 조건부 필터링 (위험 감지)
   ✅ 2D 배열 (센서 매트릭스)
   ✅ GPS 좌표 처리
   ✅ 경로 생성 및 거리 계산
   ✅ 장애물 감지 및 안전 반경 체크

🚗 다음은 Pandas로 주행 데이터를 분석해보겠습니다!
